name: Frontend Tests

on:
  push:
    paths:
      - 'tunti/tunti-frontend/**'
  pull_request:
    paths:
      - 'tunti/tunti-frontend/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: tunti/tunti-frontend

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test