name: Frontend Tests

on:
  push:
    branches:
      - github-actions-setup  # Specify your branch name here
    paths:
      - 'tunti/tunti-frontend/**'
  pull_request:
    branches:
      - github-actions-setup  # Specify your branch name here
    paths:
      - 'tunti/tunti-frontend/**'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run tests on'
        required: true
        default: 'github-actions-setup'

jobs:
  test:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: tunti/tunti-frontend

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.branch || github.ref }}

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test