name: API Call Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - hello-world-action

permissions:
  contents: write  # Default permission for all jobs

jobs:
  api-call:
    runs-on: ubuntu-latest
    permissions:
      issues: write  # Specific permission for this job only

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Data Directory
        run: mkdir -p data

      - name: Create Test JSON File
        run: echo '{"message": "This is a test file."}' > data/testfile.json

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/testfile.json
          git commit -m "Add test JSON file"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}  # Use GitHub token for authentication
