name: Test Setup

on:
  # Trigger on push to your specific branch
  push:
    branches:
      - github-actions-setup
  # Also allow manual trigger
  workflow_dispatch:

jobs:
  test-setup:
    runs-on: ubuntu-latest
    
    steps:
      - name: Print hello
        run: echo "Hello from GitHub Actions!"
      
      - name: Check environment
        run: |
          echo "Runner OS: ${{ runner.os }}"
          echo "GitHub Actor: ${{ github.actor }}"
          echo "GitHub Ref: ${{ github.ref }}"
          
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: List repository contents
        run: ls -la